views:
  - title: Hintatiedot
    path: hintatiedot
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: sensor.porssari_price_now
                name: Sähkön hinta nyt
              - entity: sensor.porssari_min_today
                name: Halvin tuntihinta tänään
              - entity: sensor.porssari_max_today
                name: Kallein tuntihinta tänään
              - entity: sensor.porssari_avg_today
                name: Sähkön keskihinta tänään
                secondary_info: last-updated
              - entity: sensor.porssari_avg_tomorrow
                name: Sähkön keskihinta huomenna
                secondary_info: last-updated
            title: Pörssäri sähkön hintatiedot
            show_header_toggle: false
          - type: entity
            entity: sensor.porssari_min_today
            attribute: Hour
            name: Halvin tunti tänään
          - type: entity
            entity: sensor.porssari_max_today
            attribute: Hour
            name: Kallein tunti tänään
      - type: custom:apexcharts-card
        graph_span: 48h
        show:
          last_updated: true
        experimental:
          color_threshold: true
        span:
          start: day
        now:
          show: true
          label: Nyt
        header:
          show: true
          title: Pörssäri sähkön hinta
          show_states: true
        yaxis:
          - min: ~0
            max: ~20
            decimals: 2
        series:
          - entity: sensor.porssari_json_data
            show:
              in_header: true
              extremas: false
              legend_value: false
            type: column
            color: lightgray
            float_precision: 2
            unit: snt/kWh
            data_generator: >
              let res = [];

              for (const [key, value] of
              Object.entries(entity.attributes.Prices)) {
                let d = new Date(key).getTime();
                if (d > 0)
                  res.push([d, value.Price]);
              }

              return res.sort((a, b) => { return a[0] - b[0] });
            color_threshold:
              - value: 0
                color: 368f39
              - value: 10
                color: a3b34d
              - value: 20
                color: ffd57e
              - value: 30
                color: f18c56
              - value: 40
                color: de425b
  - title: Ohjaustiedot
    badges: []
    cards:
      - type: entities
        entities:
          - entity: sensor.porssari_channel_1_state
            name: Kanava 1
            secondary_info: last-changed
          - entity: sensor.porssari_channel_2_state
            name: Kanava 2
            secondary_info: last-changed
          - entity: sensor.porssari_channel_3_state
            name: Kanava 3
            secondary_info: last-changed
          - entity: sensor.porssari_channel_4_state
            name: Kanava 4
            secondary_info: last-changed
          - entity: sensor.porssari_channel_5_state
            name: Kanava 5
            secondary_info: last-changed
          - entity: sensor.porssari_channel_6_state
            name: Kanava 6
            secondary_info: last-changed
          - entity: sensor.porssari_channel_7_state
            name: Kanava 7
            secondary_info: last-changed
          - entity: sensor.porssari_channel_8_state
            secondary_info: last-changed
            name: Kanava 8
        state_color: true
        title: Kanavaohjauksen tila nyt
      - type: logbook
        entities:
          - sensor.porssari_channel_1_state
          - sensor.porssari_channel_2_state
          - sensor.porssari_channel_3_state
          - sensor.porssari_channel_4_state
          - sensor.porssari_channel_5_state
          - sensor.porssari_channel_6_state
          - sensor.porssari_channel_7_state
          - sensor.porssari_channel_8_state
        title: Kanavaohjaushistoria
        hours_to_show: 24
  - title: Asetukset
    path: asetukset
    badges: []
    cards:
      - type: entities
        entities:
          - entity: input_text.porssari_mac
          - entity: binary_sensor.porssari_json_prices
            name: Päivän hintatiedot käytettävissä
          - entity: binary_sensor.porssari_json_controls
            name: JSON-ohjaustieto käytettävissä
            secondary_info: none
          - entity: sensor.porssari_json_data
            secondary_info: last-updated
            name: JSON-aikaleima
          - entity: sensor.porssari_request
            name: Viimeisimmän kyselyn tila
            secondary_info: none
        title: Pörssäri asetukset